apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "second-nfs-client"