apiVersion: v1
kind: Pod
metadata:
  name: vault-config-init
  namespace: vault
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: vault-config-storage
      mountPath: /mnt/vault-config
  volumes:
  - name: vault-config-storage
    persistentVolumeClaim:
      claimName: vault-config-pvc
  restartPolicy: Never
